[build]
  functions = "netlify/functions"
  publish = "Day 1"

[dev]
  functions = "netlify/functions"
  publish = "Day 1"

[[redirects]]
  from = "/"
  to = "/Home Page/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/Contact Us Page/contact.html"
  status = 200 