[build]
  functions = "netlify/functions"
  publish = "Day 1"

[dev]
  functions = "netlify/functions"
  publish = "Day 1"

[[redirects]]
  from = "/"
  to = "index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "contact.html"
  status = 200 